### PR TITLE
update to current mmm-voice level

### PR DESCRIPTION
**Pull request by sdetweil**

### CODE REVIEW

**Comment by mykle1** [comment]
I was going to merge your PR but I was presented with this error message. "This branch has conflicts that must be resolved"

**Comment by sdetweil** [comment]
Ok, will resolve and let u know

**Comment by sdetweil** [comment]
MMM-Voice author has not promoted my change to master.. so still have to wait.. , sorry for the confusion

**Comment by mykle1** [comment]
Sam, I closed the pull request because it doesn't seem necessary anymore, now that Lucy has a significant re-write. I continue to be very appreciative of all your help.

**Pull request closed without merging**
